export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE';

export const LOGIN_HOSPITAL_REQUEST = 'LOGIN_HOSPITAL_REQUEST'
export const LOGIN_HOSPITAL_SUCCESS = 'LOGIN_HOSPITAL_SUCCESS'
export const LOGIN_HOSPITAL_FAILURE = 'LOGIN_HOSPITAL_FAILURE'

export const LOGIN_PACIENTE_REQUEST = 'LOGIN_PACIENTE_REQUEST'
export const LOGIN_PACIENTE_SUCCESS = 'LOGIN_PACIENTE_SUCCESS'
export const LOGIN_PACIENTE_FAILURE = 'LOGIN_PACIENTE_FAILURE'

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

